- README.md
- libraries/chef_ingredient_resource.rb
- libraries/chef_server_ingredient_shim.rb
- libraries/ingredient_config_provider.rb
- libraries/ingredient_config_resource.rb
- libraries/omnibus_service_resource.rb
- spec/unit/recipes/test_repo_spec.rb
- test/fixtures/cookbooks/test/recipes/repo.rb
Fixes https://github.com/chef-cookbooks/chef-ingredient/issues/17. /cc @jtimberman
> Add sensitive attribute to ingredient-config.

- libraries/matchers.rb
Cannot use chefspec on ingredient_config resource
> Missing matcher for ingredient_config

- PRODUCT_MATRIX.md
- libraries/helpers.rb
Adds support for the [chef marketplace](https://github.com/chef-partners/omnibus-marketplace) addon
> Add chef-marketplace support

- .kitchen.yml
- CHANGELOG.md
- README.md
- libraries/ingredient_config_provider.rb
- libraries/ingredient_config_resource.rb
- libraries/matchers.rb
- metadata.rb
- spec/unit/recipes/test_ingredient_config_spec.rb
- test/fixtures/cookbooks/test/recipes/ingredient_config.rb
- test/integration/ingredient_config/serverspec/test_ingredient_config_spec.rb
Not sure I love the action name
> ingredient_config add

- libraries/rhel_handler.rb
> Pin the channel correctly on RHEL.

- .travis.yml
- libraries/chef_ingredient_provider.rb
- libraries/chef_server_ingredient_shim.rb
- libraries/helpers.rb
- libraries/ingredient_config_provider.rb
- libraries/omnibus_service_provider.rb
- libraries/omnitruck_handler.rb
- metadata.rb
- spec/spec_helper.rb
- spec/unit/libraries/chef_ingredient_provider_spec.rb
- spec/unit/libraries/chef_ingredient_resource_spec.rb
- spec/unit/recipes/test_config_spec.rb
- test/fixtures/cookbooks/test/recipes/config.rb
Re opening this to avoid any force push! 
https://github.com/chef-cookbooks/chef-ingredient/pull/48 **Couple small fixes so master branch backwards compatible to previously released version**
> Fixing chef-ingredient from previous released version

- .kitchen.yml
- libraries/helpers.rb
- libraries/omnitruck_handler.rb
- test/integration/chefdk/serverspec/test_chefdk_spec.rb
- test/integration/helpers/serverspec/spec_helper.rb
Allow OmnitruckHandler to install  and upgrade packages on Windows using current mixlib-install
@sersut @jtimberman
> omnitruck handler windows implementation

- .travis.yml
- Gemfile
- libraries/helpers.rb
- libraries/omnitruck_handler.rb
- recipes/default.rb
- spec/unit/recipes/test_repo_spec.rb
> Bump mixlib-install version we use to pick up the latest chef-backend changes.

- Gemfile
- libraries/helpers.rb
- libraries/omnitruck_handler.rb
@chef-cookbooks/engineering-services 
- needs to be updated with the new `mixlib-install` version as well...
> Add guard clause for windows vs other install resources

- .kitchen.yml
- .rubocop.yml
- libraries/debian_handler.rb
- spec/unit/recipes/test_repo_spec.rb
@chef-cookbooks/engineering-services
> Updating tests and code so Ubuntu 10 works :(

- libraries/debian_handler.rb
- spec/unit/recipes/test_repo_spec.rb
@chef-cookbooks/engineering-services
> Add exception for debian 6 based things

- .kitchen.yml
- attributes/default.rb
- libraries/default_handler.rb
- libraries/helpers.rb
@chef-cookbooks/engineering-services @schisamo @sersut
> update to mixlib-install 1.0.3 and remove artifactory creds logic

- CHANGELOG.md
- libraries/helpers.rb
- metadata.rb
/cc: @chef-cookbooks/engineering-services
> Prepare for 0.18.0 release

- CHANGELOG.md
- libraries/helpers.rb
- metadata.rb
@chef-cookbooks/engineering-services
> install latest mixlib-install from Rubygems

- .kitchen.yml
- .travis.yml
- Gemfile
- libraries/chef_ingredient_resource.rb
- libraries/helpers.rb
- spec/unit/recipes/test_delivery_cli_spec.rb
- test/fixtures/cookbooks/test/recipes/delivery_cli.rb
- test/integration/delivery_cli_yolo/serverspec/delivery_cli_spec.rb
This PR is the chef-ingredient side of https://github.com/chef/mixlib-install/pull/107. 
/cc: @chef-cookbooks/engineering-services
> platform_version compatibility mode

- resources/ingredient_config.rb
> Fixes invalid property type 'nil'

- spec/unit/recipes/test_config_spec.rb
- spec/unit/recipes/test_custom_repo_setup_recipe_spec.rb
- spec/unit/recipes/test_local_spec.rb
- spec/unit/recipes/test_push_spec.rb
- spec/unit/recipes/test_repo_spec.rb
- spec/unit/recipes/test_upgrade_spec.rb
- tasks/maintainers.rb
- test/fixtures/cookbooks/test/recipes/custom_repo_setup_recipe.rb
> Use node.normal not node.set in testing

- libraries/default_handler.rb
- libraries/helpers.rb
- resources/chef_ingredient.rb
- spec/unit/recipes/test_repo_spec.rb
Utilize latest mixlib-install 3.x release
Updated resource to according to the latest changes
> Update mixlib-install to 3.x

- resources/chef_ingredient.rb
Issue #140 
Although this seems to work locally and in dcc this issue did arise in shd. Perhaps changing the include to use a global constant lookup will provide consistency.
@schisamo @smith 
> update handlers to use a global constant lookup

- libraries/helpers.rb
Related to PR: https://github.com/chef/mixlib-install/pull/200
https://github.com/chef/mixlib-install/issues/199
> normalize auto-detected architectures

- CHANGELOG.md
- libraries/helpers.rb
- metadata.rb
> mixlib-install gem 3.2

- .kitchen.appveyor.yml
- .kitchen.dokken.yml
- .kitchen.yml
- .travis.yml
- appveyor.yml
- test/integration/chefdk/test_chefdk_spec.rb
I feel better by having a few chef 12 acceptance tests running...
> Acceptance tests for Chef 12 and 13

- CHANGELOG.md
- MAINTAINERS.md
- metadata.rb
> prepare 2.0.5 release

- libraries/helpers.rb
- resources/chef_ingredient.rb
Account for internal Chef repo mapping. 
> add platform and platform version remapping logic from omnibus

- CHANGELOG.md
- metadata.rb
> prepare 2.1.0 release

- appveyor.yml
- libraries/helpers.rb
Normalize archs when auto-detected and when set
@scotthain 
> normalize architecture before setting option

- .kitchen.dokken.yml
- .travis.yml
- tasks/maintainers.rb
> Fix Chef 12 testing in kitchen-dokken

- libraries/helpers.rb
- test/integration/chef_server/test_chef_server_spec.rb
- test/integration/chefdk/test_chefdk_spec.rb
- test/integration/inspec/inspec_spec.rb
Signed-off-by: Scott Hain <shain@chef.io>
Pulls in change that fixes windows platform detection and some other bugs.
@chef-cookbooks/engineering-services 
> Bump mixlib-install version pinning

- resources/ingredient_config.rb
> Resolve CHEF-19 deprecation warnings

- resources/chef_org.rb
Signed-off-by: Nathan Cerny <ncerny@gmail.com>
> Fix remove_users to use new_resource instead of current_resource.

- resources/automate.rb
- resources/wf_builder.rb
- spec/unit/chef_automate_spec.rb
- test/fixtures/cookbooks/test/recipes/automate.rb
- test/fixtures/cookbooks/test/recipes/default.rb
- test/fixtures/cookbooks/test/recipes/install_git.rb
Signed-off-by: Nathan Cerny <ncerny@gmail.com>
There are several new bugs in the chef_stack resources due to changes in chef-client, automate, and delivery-cli.
https://github.com/ncerny/chef_stack/issues/32
https://github.com/ncerny/chef_stack/issues/33
https://github.com/ncerny/chef_stack/issues/34
> Multiple fixes for Automate and Workflow Builder resources.

- resources/server.rb
- spec/unit/recipes/test_chef_server_noaddons.rb
- spec/unit/recipes/test_chef_server_senstitive.rb
- test/fixtures/cookbooks/test/recipes/chef_server_noaddons.rb
- test/fixtures/cookbooks/test/recipes/chef_server_sensitive.rb
Update tests
This resolves issue #176 
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
> Allow chef-server install without addons

- CHANGELOG.md
- metadata.rb
> Release 2.2.0

- .github/CODEOWNERS
Signed-off-by: Seth Chisamore <schisamo@chef.io>
> Send all notifications to the Package Distribution Maintainers

- resources/wf_builder.rb
Signed-off-by: gscho <greg.c.schofield@gmail.com>
Adds `new_resource.` in a few places that were missing it.
N/A
> Add missing new_resource. to wf_builder

- .kitchen.dokken.yml
- .kitchen.yml
- .travis.yml
- libraries/default_handler.rb
- libraries/helpers.rb
- spec/unit/recipes/test_default_handler_spec.rb
- spec/unit/recipes/test_push_spec.rb
- test/fixtures/cookbooks/test/recipes/chef_server.rb
- test/fixtures/cookbooks/test/recipes/chef_server_sensitive.rb
Get this cookbook passing again
> Testing updates

- spec/unit/chef_automate_spec.rb
Skipping test and submitting issue to chefspec project
> skip test due to chefspec 7.2.1 issue

- resources/chef_org.rb
> revert chef_org user/admin guards (PR#223)

- .travis.yml
- README.md
- appveyor.yml
- kitchen.yml
- metadata.rb
- resources/automatev2.rb
- test/fixtures/cookbooks/test/recipes/automatev2.rb
- test/integration/chef_automatev2/test_chef_automatev2_spec.rb
Signed-off-by: Corey Hemminger <hemminger@hotmail.com>
adds resource for installing chef automate version 2
> Add automatev2 resource

- resources/automatev2.rb
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
- Minor typo fix for chef-automate path
Fixes https://github.com/chef-cookbooks/chef-ingredient/issues/246
> Fix typo for automate path

- .travis.yml
- appveyor.yml
- chefignore
- kitchen.dokken.yml
- kitchen.yml
- resources/automate.rb
- resources/automatev2.rb
- resources/backend.rb
- resources/chef_org.rb
- resources/chef_user.rb
- resources/client.rb
- resources/file.rb
- resources/server.rb
- resources/supermarket.rb
- resources/wf_builder.rb
- spec/unit/recipes/test_omnibus_service_spec.rb
- test/fixtures/cookbooks/test/recipes/chefdk.rb
- test/fixtures/cookbooks/test/recipes/custom_repo_setup_recipe.rb
- test/fixtures/cookbooks/test/recipes/omnibus_service.rb
- test/integration/chefdk/test_chefdk_spec.rb
- test/integration/inspec/inspec_spec.rb
added provides line along with resource_name for chef 16 and backwards compatability
chef-infra client 16 backwards compatability
> added provides to resources to add chef 16 compatability
