chef-cookbooks/chef-ingredient

PRODUCT_MATRIX.md, README.md, libraries/chef_ingredient_provider.rb, libraries/chef_ingredient_resource.rb, libraries/helpers.rb, libraries/omnibus_service_resource.rb, spec/centos_65_spec.rb, spec/omnibus_service_spec.rb, spec/ubuntu_1404_spec.rb, test/fixtures/cookbooks/test/recipes/local.rb, test/fixtures/cookbooks/test/recipes/omnibus_service.rb, test/fixtures/cookbooks/test/recipes/repo.rb, test/integration/default/serverspec/default_spec.rb, test/integration/local_package_install/serverspec/assert_local_package_installed_spec.rb, test/integration/override_package_versions/serverspec/assert_package_version_installed_spec.rb
Fixes #1.
Implements a product matrix and product_lookup method that returns a
hash of product information based on the table in #1, with naming
conventions updated to upcoming product updates. It attempts to be
smart so users of the chef_ingredient resource don't need to know the
underlying details about our package naming, especially wrt old
package names.
The product_lookup method also validates that the chef-server package
is selected properly based on the available, supported versions (12
and 11), and fails if the version is specified as > 1.0 and < 11.0,
since we did not publish omnibus packages for those versions.
Add the version attribute to the omnibus_service resource so it can
properly look up the ctl command.
=> Use product keys as the name attribute

README.md, libraries/chef_ingredient_provider.rb, libraries/chef_ingredient_resource.rb, libraries/helpers.rb, libraries/omnibus_service_provider.rb, libraries/omnibus_service_resource.rb, spec/centos_65_spec.rb, spec/omnibus_service_spec.rb, spec/ubuntu_1404_spec.rb
Also cleans up rubocop and foodcritic warnings, because hey.
=> Fixes #3, allow latest and remove package_name

.kitchen.yml, libraries/chef_ingredient_provider.rb, libraries/chef_ingredient_resource.rb, libraries/helpers.rb, libraries/matchers.rb, spec/unit/recipes/test_repo_spec.rb, spec/unit/recipes/test_upgrade_spec.rb, test/fixtures/cookbooks/test/recipes/upgrade.rb
Move the install action content to new methods that return the right
resources etc so we can use those methods in an install or upgrade
action.
@chef-cookbooks/engineering-services @ryancragun
=> Add upgrade action to chef_ingredient

.kitchen.yml, chefignore, libraries/helpers.rb, spec/unit/recipes/test_push_spec.rb, test/fixtures/cookbooks/test/attributes/default.rb, test/fixtures/cookbooks/test/recipes/push.rb
Unfortunately we can't test this on Ubuntu 14.04 in kitchen as the
push client packages aren't pushed to the trusty distro on
packagecloud yet.
However, the specs work, and downstream users can add the repository
with "precise" as the codename instead of "trusty," so there's that.
=> Add push client test, fix naming for old packages

libraries/chef_ingredient_resource.rb, libraries/chef_server_ingredient_shim.rb, libraries/ingredient_config_resource.rb, libraries/omnibus_service_resource.rb
Looks like `resource_name` setter has been in the DSL since Chef 12.0.0:
https://github.com/chef/chef/blob/12.0.0/lib/chef/resource/lwrp_base.rb#L61
I think we can safely switch to using these @jtimberman.
Fixes: https://github.com/chef-cookbooks/chef-ingredient/issues/16
=> Use recipe DSL to set the resource name.

libraries/chef_ingredient_provider.rb
I have a cookbook where I'm currently only using the `:reconfigure` action.  I was getting a LoadError.
```
LoadError
---------
cannot load such file -- mixlib/versioning
```
This PR should allow the use of any of the actions even if `:install` or `:upgrade` are not previously called (since they install the gem)
=> ensure mixlib-versioning is installed for all actions

libraries/ingredient_config_provider.rb
Setting the owner and permissions on the config file's directory
conflicts with product ctl commands that also manage those
directories. For example some have the ownership set to opscode
instead of root, meaning this is updated every time and causes a
reconfigure to run again, extending the length of time it takes to
converge a node.
=> Fixes #26, remove the ownership and permissions

libraries/chef_ingredient_provider.rb, libraries/chef_server_ingredient_shim.rb, libraries/ingredient_config_provider.rb, libraries/omnibus_service_provider.rb, spec/unit/recipes/test_push_spec.rb, spec/unit/recipes/test_repo_spec.rb, spec/unit/recipes/test_upgrade_spec.rb
Add provides in providers to get rid of noisy warnings
Test that we're getting the right provider (yum or apt) for the
different platforms by using ChefSpec's runner lookup method
`#find_resource`. We want to ensure that the returned resource is not
nil, uses the correct resource class, and finally that it's a package
resource with an install action.
=> Fix rspec failures and warnings

libraries/helpers.rb
As a user I would like to use `chef_ingredient` and setup my supermarket server passing my configuration through the `config` attribute so I don't have to use other methods like a `template` or `file` resources to lay down my configuration.
**Solution**
This commit modified the `product_matrix` pointing to the right `config-file` for supermarket that is `/etc/supermarket/supermarket.json` 
Closes https://github.com/chef-cookbooks/chef-ingredient/issues/30
=> Correct supermarket config file in product_matrix

libraries/omnibus_service_provider.rb
Fixes a syntax error
```
================================================================================
Recipe Compile Error in /opt/chef-marketplace/embedded/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb
================================================================================
SyntaxError
-----------
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.0.current.0/lib/chef/provider.rb:282: syntax error, unexpected '-', expecting ';' or '\n'
def action_graceful-kill
^
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.0.current.0/lib/chef/provider.rb:286: syntax error, unexpected keyword_ensure, expecting end-of-input
Cookbook Trace:
---------------
/opt/chef-marketplace/embedded/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb:34:in …
```
=> Fix syntax error in omnibus_service_provider

README.md, libraries/helpers.rb
This also fixes this issue:
- https://github.com/chef-cookbooks/chef-server/issues/105
=> Fixes #35, implement fqdn_resolves? method

.gitignore, .kitchen.yml, .rubocop.yml, .travis.yml, Berksfile, Gemfile, README.md, Rakefile, libraries/chef_ingredient_provider.rb, libraries/chef_ingredient_resource.rb, libraries/debian_handler.rb, libraries/helpers.rb, libraries/matchers.rb, libraries/omnitruck_handler.rb, libraries/omnitruck_helpers.rb, libraries/rhel_handler.rb, metadata.rb, spec/unit/recipes/test_chef_spec.rb, spec/unit/recipes/test_different_channels.rb, spec/unit/recipes/test_ingredient_config_spec.rb, spec/unit/recipes/test_push_spec.rb, spec/unit/recipes/test_upgrade_spec.rb, test/fixtures/cookbooks/test/recipes/chef.rb, test/fixtures/cookbooks/test/recipes/chefdk.rb, test/fixtures/cookbooks/test/recipes/different_channels.rb, test/fixtures/cookbooks/test/recipes/ingredient_config.rb, test/integration/chefdk/serverspec/test_chefdk_spec.rb, test/integration/different_channels/serverspec/assert_install_from_different_repos_spec.rb
```ruby
chef_ingredient "chef" do
action :install
version '12.5.0'
channel :current # default is :stable
end
chef_ingredient 'chef' do
action :install
channel :stable
end
chef_ingredient 'chef' do
action :upgrade
channel :current
end
```
Supporting versions other than `:latest` (as explained in https://github.com/chef-cookbooks/chef-ingredient/issues/39) is not in the scope of this work.
There are two remaining items but will have different PRs for them since this is already a monster PR:
- Implement channel pinning on RHEL.
- Enable installations from omnitruck.
=> Auto update for debian / rhel platforms & refactoring to support omnitruck

Berksfile, Policyfile.rb, README.md, spec/spec_helper.rb
- Remove berksfile
- Use policyfile w/ ChefSpec
- Configure RSpec for color, doc formatter, and error log level
=> We use ChefDK 0.9.0 and policyfiles

.kitchen.yml, metadata.rb
We need to use >= instead of ~> for version constraints because Chef
Policies use "dotted decimal identifier" versions that result in
integers that will never match the "normal" cookbook versions we use.
For example, the version constraint:
~> 3.2
is what we used. However, the dotted decimal version may be
30625036585770760.42672982950081083.162968991950205
The dotted decimal version is used in the "backwards compatibility
mode" for Chef Zero as it doesn't have the native Policy document API
(yet). This may result in a 412 precondition failed exception when
using the pessmistic version constraint.
=> Relax version constraints for dependencies

libraries/chef_ingredient_provider.rb, libraries/ingredient_config_provider.rb, libraries/omnibus_service_provider.rb
In commit c3f44ac, `use_inline_resources` was commented out. It is required in the `chef_ingredient` resource:
1. We send notifications in the various action helper methods that rely on operating against resources in the context of the `chef_ingredient` resource
2. It's the default in Chef 12.5 custom resources because the interaction is better for resources that are composed of other Chef resources as `chef_ingredient`
=> We must use_inline_resources

libraries/helpers.rb
Because of the way we manipulate run contexts in resources, and resource
event notifications, we need to ensure that we aren't accumulating the
configuration file content multiple times when the `add_config` method
is used.
=> Content accumulator guard

.gitignore, PRODUCT_MATRIX.md, chefignore, libraries/helpers.rb
This change fixes a number of errors WRT to naming of the Push Jobs client and server product keys, packages and ctl commands.
This should now reflect the true state of the world.
/cc @stephenlauck @chef-cookbooks/engineering-services
=> Fix Push Jobs naming issues

CHANGELOG.md, Policyfile.rb, attributes/default.rb, libraries/debian_handler.rb, libraries/helpers.rb, libraries/rhel_handler.rb, metadata.rb, spec/unit/recipes/test_custom_repo_setup_recipe_spec.rb, test/fixtures/cookbooks/custom_repo/metadata.rb, test/fixtures/cookbooks/custom_repo/recipes/awesome_custom_setup.rb, test/fixtures/cookbooks/test/metadata.rb, test/fixtures/cookbooks/test/recipes/custom_repo_setup_recipe.rb
Provides the ability to "Bring Your Own Repo Setup Recipe" for companies
where direct connections to the internet are not possible.
Setting `node['chef-ingredient']['custom_repo_setup_recipe']` pointing
to your own repository setup recipe will avoid the creation of any
**chef** specific repo pointing to packagecloud.
Closes https://github.com/chef-cookbooks/chef-ingredient/issues/62
=> Do not assume connection to the interwebs

.kitchen.yml, Gemfile, README.md, libraries/chef_ingredient_resource.rb, libraries/helpers.rb, test/fixtures/cookbooks/test/recipes/unstable.rb
This PR enables `chef-ingredient` to install Chef Client and Chef DK from unstable channel. 
/cc: @chef-cookbooks/engineering-services
=> Enable installation of chef and chefdk from unstable channel.

.kitchen.yml, Berksfile, attributes/default.rb, libraries/chef_ingredient_provider.rb, libraries/chef_ingredient_resource.rb, libraries/debian_handler.rb, libraries/helpers.rb, libraries/omnitruck_handler.rb, libraries/rhel_handler.rb, test/fixtures/cookbooks/test/metadata.rb, test/fixtures/cookbooks/test/recipes/compliance.rb, test/fixtures/cookbooks/test/recipes/unstable_chef_server.rb, test/fixtures/cookbooks/test/recipes/unstable_chefdk.rb
The core changes here are in DebianHandler and RhelHandler.  The `configure_package` has been split to support custom repos, source packages, and unstable channel using mixlib-install.
This PR also includes maintenance updates for rubocop and foodcritic.
Known Issues:
* chefdk upgrade kitchen tests are still broken (known issue)
* Unstable channel resolution not supported for Windows (a new PR will be created to add a WindowsHandler)
* Handlers contain some similar and duplicated code.  This should be fixed when we implement the WindowsHandler.
TODOs:
- [ :heavy_check_mark: ] Remove local test code (synced folders, chef_gem install)
- [ :heavy_check_mark: ] release next mixlib-install alpha version and update cookbook
@sersut
=> Add support for unstable channel to Debian and RHEL handlers

libraries/chef_ingredient_provider.rb, libraries/helpers.rb, spec/unit/recipes/test_push_spec.rb
This PR deprecates chef-ha, chef-marketplace, chef-sync, push-client, push-server in favor of ha, marketplace, sync, push-jobs-client, push-jobs-server.
As we are moving to bintray, we have standardized these names in mixlib-install with https://github.com/chef/mixlib-install/pull/77/files . This PR makes sure that backwards compatibility is not broken for changed products. 
Fixes https://github.com/chef-cookbooks/chef-ingredient/issues/89. 
Note that `0.8.0.alpha.8` is the first version of mixlib-install where these new naming is introduced.
/cc: @chef-cookbooks/engineering-services
=> Deprecate non-standard product names.

README.md, libraries/chef_ingredient_provider.rb, libraries/chef_ingredient_resource.rb, libraries/helpers.rb, resources/ingredient_config.rb, spec/unit/recipes/test_config_spec.rb, test/fixtures/cookbooks/test/recipes/config.rb
This PR add `accept_license` property to chef-ingredient so the users can set it to be able to reconfigure compliance, manage, reporting and analytics after the version that supports `--accept-license` during reconfigure ships. 
@mmzyk note that this PR needs the minimum version numbers that support `--accept-license` CLI option. I have set them to be a minor version bump with the current existing ones. If we would like to set a different version let me know.
/cc: @chef-cookbooks/engineering-services @alexpop
=> Add accept_license property to chef-ingredient.

libraries/chef_ingredient_resource.rb, resources/ingredient_config.rb, spec/unit/recipes/test_repo_spec.rb
The `default: nil` doesn't actually do anything, but in a world of `nil` setters, it will actively be wrong unless `nil` becomes a valid value for the resource.
=> Get rid of default: nil warnings

libraries/default_handler.rb
Converge_by is used to say "Here's a thing that is definitely changing",
showing a green entry in the chef run output, marking the resource as changed,
and being skipped in why_run mode.
However, in this case, the thing inside the converge_by is a resource itself
(remote_file), which has all the previous properties. In addition, no testing
is done before the converge_by, meaning a change is registered (and a message
saying 'Downloading X' in green is shown) every time, regardless of whether an
actual file is downloaded by the remote_file resource.
Removing the converge by fixes this behavior, and if a file is actually
downloaded then the remote_file resource will say so with a 'create new file'
message.
Refs #102
=> Remove extraneous converge_by

libraries/chef_ingredient_provider.rb, libraries/default_handler.rb, spec/unit/recipes/test_handlers_spec.rb, test/fixtures/cookbooks/test/recipes/handlers.rb
Add SUSE platform to use DefaultHandler (mixlib-install) rather than the OmnitruckHandler.
OmnitruckHandler is currently broken, and we want to use the DefaultHandler whenever possible.
=> Update SUSE platform to use DefaultHandler

libraries/omnitruck_handler.rb
Removed `notifies` for `file` resources in OmnitruckHandler. Once we enter the `configure_version` 
method we should be running the install.
I tested this manually since I'm not sure the best way to validate repeated CCR failures with test-kitchen.
Fixes issue where once a CCR fails, and subsquent CCR would not.
=> Fix issue when a subsequent CCR doesn't fail as expected with OmnitruckHandler

Rakefile, libraries/helpers.rb, metadata.rb
Prior to 12.16.3 we had some bugs in compat_resource that caused a lot of failures on older chef-client releases. We should depend on a working version.
=> Depend on the latest compat_resource + cookstyle fixes

libraries/default_handler.rb
windows_package (created during converge by chef_ingredient => package => windows_package) will use the timeout for the install process (defaults to 600).  Attempted this same change in a [previous PR](https://github.com/chef-cookbooks/chef-ingredient/pull/117), but I didn't respond to the maintainer's question in a timely manner and it was closed.  Evidence of how the timeout attribute is used is shown in the links below:
https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/default_handler.rb#L60
https://github.com/chef-cookbooks/windows/blob/master/libraries/windows_package.rb#L207
https://github.com/chef-cookbooks/windows/blob/master/libraries/windows_package.rb#L108
After making this change we stopped getting intermittent timeouts while attempting to run the push …
=> Added timeout to package resource created by configure_from_source_package 

.kitchen.yml, README.md, libraries/chef_ingredient_resource.rb, libraries/default_handler.rb, libraries/helpers.rb, spec/unit/recipes/test_override_platform_spec.rb, spec/unit/recipes/test_repo_spec.rb, test/fixtures/cookbooks/test/recipes/override_platform.rb
Add platform overrides for the chef_ingredient resource. This will allow users to customize specific packages to be installed. Specifically in cases where the auto-detection logic is returning unfavorable results.
Created a basic unit test for the attributes and manually tested a kitchen suite.
JEX-384
@schisamo @chef-cookbooks/engineering-services
=> add platform detail override attributes

libraries/helpers.rb
This verison of mixlib-install contains an important compat fix related to the recent delivery -> automate package rename:
https://github.com/chef/mixlib-install/pull/177
Signed-off-by: Seth Chisamore <schisamo@chef.io>
/cc @chef-cookbooks/engineering-services
=> Ensure we install mixlib-install >= 2.1.12

.kitchen.yml, README.md, metadata.rb
=> Require Chef 12.5+ and remove compat_resource dependency

.kitchen.dokken.yml, .kitchen.yml, .travis.yml, metadata.rb, resources/ingredient_config.rb, test/fixtures/cookbooks/test/recipes/chefdk.rb, test/integration/chefdk/test_chefdk_spec.rb, test/integration/default/default_spec.rb, test/integration/helpers/serverspec/spec_helper.rb, test/integration/local_package_install/assert_local_package_installed_spec.rb
This is provided by chef-client on all resources now. Including it here
breaks runs on Chef 13. This PR also adds integration testing in Travis CI with kitchen-dokken and converts from Serverspec to InSpec.
=> Remove sensitive property for Chef 13 compatibility

Guardfile
Signed-off-by: Nathan Cerny <ncerny@gmail.com>
Cookstyle reports warnings when using // regex syntax.  This updates the Guardfile to %r{} syntax.
=> Fix regex style to match cookstyle recommendations.

libraries/default_handler.rb, libraries/helpers.rb, spec/unit/recipes/test_custom_repo_setup_recipe_spec.rb
Debian 6 and Ubuntu 10 are EOL. The latest fauxhai release doesn't recognize these platforms. Time to remove support from chef-ingredient.
=> Remove debian 6 and ubuntu 10 support

.kitchen.appveyor.yml, .kitchen.yml, appveyor.yml, libraries/default_handler.rb, resources/chef_ingredient.rb, test/fixtures/cookbooks/test/recipes/chefdk.rb, test/fixtures/cookbooks/test/recipes/inspec.rb, test/integration/chefdk/test_chefdk_spec.rb, test/integration/inspec/inspec_spec.rb
chef_ingredient packages installs break on Windows using Chef 13. This fixes the issue and updates tests.
#155
=> update chef_ingredient resource timeout property to be chef 13 compliant

libraries/helpers.rb, resources/chef_ingredient.rb
This logic is not necessary. I believe it was there pre-mixlib-install. Now, mixlib-install handles verifying the product name and returning valid products. 
@iennae This should make things easier :)
@chef-cookbooks/engineering-services 
#158
=> remove #check_deprecated_properties

.kitchen.yml, CHEFSTACK.md, libraries/helpers.rb, resources/automate.rb, resources/backend.rb, resources/chef_org.rb, resources/chef_user.rb, resources/client.rb, resources/file.rb, resources/server.rb, resources/supermarket.rb, resources/wf_builder.rb, templates/default/client.rb.erb, templates/default/push-jobs-client.rb.erb, test/fixtures/cookbooks/test/recipes/chef_server.rb, test/integration/chef_server/test_chef_server_spec.rb
Move chef_stack resources into chef-ingredient
This PR includes the essentials: the resources, templates, helpers and docs
I did not include the test/fixtures/config directory in this PR as no files were created when I ran the chef-services kitchen tests. I didn't dig into this aspect deeply, but looks simple enough to make adjustments.
Please make suggestions for what other comments and references anyone would like to add.
=> Merge Chef Stack resources and helpers

libraries/helpers.rb, resources/chef_ingredient.rb
- Remove logic ported from omnibus
- Remove default values from platform-related properties
- Reinstate Mixlib Install platform detection
- Never modify platform-related properties when explicity set
- Auto-detect and set platform-related properties when not explicity set
#168
=> Reinstate mixlib install platform mapping logic

libraries/default_handler.rb, spec/unit/recipes/test_local_spec.rb
Use the default package provider for RHEL and SuSE instead of hardcoding RPM as the package provider.
#181
=> use default package provider on RHEL and SuSE instead of RPM; fixes #181

resources/chef_org.rb
…s, and remove_users.
fix deprecation warnings for chef_org resource.
>          rename users to current_resource.users at 1 location:
>            - /tmp/kitchen/cache/cookbooks/chef-ingredient/resources/chef_org.rb:53:in `block in class_from_file'
>           See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
>          rename admins to new_resource.admins at 1 location:
>            - /tmp/kitchen/cache/cookbooks/chef-ingredient/resources/chef_org.rb:60:in `block in class_from_file'
>           See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
>          rename remove_users to current_resource.remove_users at 1 location:
>            - /tmp/kitchen/cache/cookbooks/chef-ingredient/resources/chef_org.rb:67:in `block in …
=> Update chef_org resource to fix deprecation warnings

libraries/default_handler.rb, spec/unit/recipes/test_default_handler_spec.rb, spec/unit/recipes/test_local_spec.rb
Engineering Services requires RHEL 5 builder support.
@chef-cookbooks/engineering-services 
=> RHEL 5 and 6 package manager support

resources/automate.rb, spec/unit/chef_automate_spec.rb
Signed-off-by: Nathan Cerny <ncerny@gmail.com>
Fixes #195
=> Fix permissions on automate keys and license.

resources/automate.rb, resources/backend.rb, resources/chef_ingredient.rb, resources/client.rb, resources/file.rb, resources/ingredient_config.rb, resources/server.rb, resources/supermarket.rb, resources/wf_builder.rb, spec/unit/chef_automate_spec.rb, spec/unit/recipes/test_chef_server_senstitive.rb, test/fixtures/cookbooks/test/recipes/automate.rb, test/fixtures/cookbooks/test/recipes/chef_server.rb, test/fixtures/cookbooks/test/recipes/chef_server_sensitive.rb
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
sensitive property set at top level resources will be passed down to resources
https://github.com/chef-cookbooks/chef-ingredient/issues/198
=> [JEX-687] Update sensitive property

libraries/helpers.rb
The chef server cookbook fails because this method was removed at some
point. This adds it back as a helper method.
Signed-off-by: JJ Asghar <jj@chef.io>
=> Required for chef_server cookbook

resources/wf_builder.rb
Signed-off-by: Christopher P. Maher <defilan@gmail.com>
This change fixes a bug where the client_key path for the file resource in wf_builder isn't correctly set. This passes the entire file path instead of the directory. 
This fixes a bug that prevents wf_builder from finishing sucessfully as it fails on creating the correct file for dbuild user in /var/opt/delivery/workspace/etc and /var/opt/delivery/workspace/.chef.
- [* ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [*] New functionality includes testing.
- [*] New functionality has been documented in the README if applicable
- [*] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentat …
=> Fixing pathing for etc and .chef directories for dbuild in wf_builder

.kitchen.dokken.yml, .kitchen.yml, README.md, libraries/default_handler.rb, resources/chef_ingredient.rb
Amazon Linux has its own platform family in Chef 13. Add it in the 2 places it needs to be. Also add it to kitchen and do a bit of cleanup while we're in the files.
=> Fix amazon linux support in Chef 13

.travis.yml, README.md, metadata.rb, resources/automate.rb, resources/backend.rb, resources/chef_ingredient.rb, resources/chef_org.rb, resources/chef_user.rb, resources/client.rb, resources/file.rb, resources/ingredient_config.rb, resources/omnibus_service.rb, resources/server.rb, resources/supermarket.rb, resources/wf_builder.rb, test/fixtures/cookbooks/test/recipes/chefdk.rb
So we had a bit of a rocky start with custom resources. 12.5 worked with class_eval, 12.6 didn't unless they were at the top of the file and a last chef 12 release (12.12/12.13 era) outright fails if you use class_eval. To get around this we require 12.7 everywhere we use custom resources and we don't do the class_eval. It works for older clients as well as new clients and 12.7 came out 18 months ago.
=> Require Chef 12.7 and stop using class_eval on action_class

README.md, resources/backend.rb
`/etc/chef-backend/chef-backend-secrets.json` must be readable by the user that the `chef-backend` services are running as in-order for cluster actions like leader failover and promotion to work.
This PR changes the mode of the secrets file from `0600` to `0640`, makes the user and group associated with the secrets file configurable, and defaults the file ownership to `root:chef_pgsql` (which is required for cluster operations to work when using default settings).
Two new properties have been added to this resource to allow for the secrets file ownership to be configurable:
```
chef_backend_secrets_user
chef_backend_secrets_group
```
=> Fix permissions on chef-backend-secrets.json

kitchen.dokken.yml, kitchen.yml
Silences the chef-25 deprecation cause by a transitive dependency (seven_zip) cookbook.
https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#silencing-deprecation-warnings
N/A
=> Silence chef-25 deprecation from seven_zip cookbook

resources/client.rb
This adds directory creation for the chef config `client.d` folder pattern which was [introduced by default in Chef Client 12.8](https://docs.chef.io/config_rb_client.html). I figure with Chef 14 being upon us that this is a good time as any to introduce this.
None
=> Add client.d folder provisioning to chef_client resource

resources/chef_org.rb
Signed-off-by: manulik <denismanulik@gmail.com>
Fix incorrect guards for chef_org resource. Current don't imply convergent execution of 'add-admin' and 'add-user' blocks
Not specified
=> Fix chef_org guards

libraries/default_handler.rb, spec/unit/recipes/test_default_handler_spec.rb
RHEL 8 now ships with dnf as the primary package manager. This fix accounts for
the need to use the Dnf package provider instead of the defaulted Yum provider.
Without this, the converge will fail trying to use the Yum provider.
Signed-off-by: Lance Albertson <lance@osuosl.org>
=> Fix support for RHEL/CentOS 8

resources/chef_ingredient.rb
Pulled this in from chef-cookbooks/chef-ingredient#241 since the original author hasn't been able to sign off on the commits and I want to upgrade to Chef Infra Server 13.
There are unrelated lint issues when I run `delivery local all`.
Pass license acceptance to `chef-server-ctl` when necessary.
=> Make Chef Infra Server honor license acceptance

.rubocop.yml, CHANGELOG.md, README.md, attributes/default.rb, libraries/default_handler.rb, libraries/helpers.rb, libraries/omnitruck_handler.rb, metadata.rb, recipes/default.rb, resources/automate.rb, resources/automatev2.rb, resources/backend.rb, resources/chef_ingredient.rb, resources/chef_org.rb, resources/chef_user.rb, resources/client.rb, resources/file.rb, resources/ingredient_config.rb, resources/omnibus_service.rb, resources/server.rb, resources/supermarket.rb, resources/wf_builder.rb, spec/unit/chef_automate_spec.rb, spec/unit/chef_file_spec.rb
Signed-off-by: Robert Detjens <detjensrobert@osuosl.org>
Enables `unified_mode` for Chef 17 compatibility. Also applys the latest Cookstyle.
(none)
Something's up with the spec tests. `PRODUCT_MATRIX` isn't being loaded, so stuff is erroring out. This also happens on the `master` branch, so not related to this PR.
Was this stubbed somewhere before and is not being loaded anymore?
=> Enable unified_mode & cookstyle fixes

resources/automate.rb, resources/client.rb, resources/wf_builder.rb
These are for EOL products or have been replaced with functionality in
the client itself.
=> Add deprecations to the automate, chef_client and wf_builder resources
